name: nextvine
description: A video recording app.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.1
  camera_android_camerax: ^0.6.18+3
  permission_handler: ^12.0.0+1
  logger: ^2.0.2+1
  path_provider: ^2.1.2
  google_fonts: ^6.1.0
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  google_sign_in: ^6.2.1
  path: ^1.9.1
  firebase_core: ^3.13.1
  firebase_storage: ^12.4.6
  http: ^1.2.1
  provider: ^6.1.5
  skeletonizer: ^2.1.0+1
  flutter_staggered_grid_view: ^0.7.0
  sensors_plus: ^6.1.2
  gal: ^2.3.2
  shared_preferences: ^2.5.3
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  tflite_flutter: ^0.11.0
  chaquopy: ^0.0.20
  firebase_auth: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  assets:
    - assets/body.png
    - assets/body_align.jpg
    - assets/back_type.png
    - assets/icon.png
    - assets/branding.png
    - assets/double_major.png
    - assets/double_thoracic.png
    - assets/lumbar.png
    - assets/normal.png
    - assets/thoracic.png
    - assets/triple.png
    - assets/model.tflite

flutter_launcher_icons:
  image_path: "assets/icon.png"
  adaptive_icon_background: "#0a828a"
  android: true
  ios: false

flutter_native_splash:
  color: "#0a828a"

  android: true
  android_12:
    icon_background_color: "#0a828a"
    color: "#0a828a"
    image: "assets/icon.png"
    branding: "assets/branding.png"
  ios: false
