name: nextvine
description: A video recording app.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.1
  camera_android_camerax: ^0.6.18+3
  permission_handler: ^12.0.0+1
  logger: ^2.0.2+1
  path_provider: ^2.1.2
  google_fonts: ^6.1.0
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  path: ^1.9.1
  firebase_core: ^3.13.1
  firebase_storage: ^12.4.6
  google_mlkit_object_detection: ^0.14.0
  http: ^1.2.1
  provider: ^6.1.5
  skeletonizer: ^2.1.0+1
  flutter_staggered_grid_view: ^0.7.0
  serious_python: ^0.9.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  assets:
    - assets/body.png
    - assets/body_align.jpg
    - app/app.zip
  